[localhost]
local ansible_connection=local ansible_python_interpreter=/usr/bin/python3 ansible_user=dicoding ansible_ssh_private_key_file=~/.ssh/id_multipass_rsa

; [mariadb-servers]
; mariadb1 ansible_host=10.135.126.46 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_multipass_rsa ansible_python_interpreter=/usr/bin/python3
; mariadb2 ansible_host=10.135.126.62 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_multipass_rsa ansible_python_interpreter=/usr/bin/python3