- hosts: localhost

  vars:
    nodes:
      - mariadb-node-1
      - mariadb-node-2
      - mariadb-node-3
  
  roles: 
    - multipass_instance

- hosts: mariadb-servers

  vars:
    cluster_name: mariadb-cluster

  roles:
    - mariadb
    - config_galera
    - check_cluster_status


